name: Run Docker and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to the latest version

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Create output directory
        run: mkdir -p output

      - name: Run Docker container with all flags
        run: docker run myapp --extract_restaurants --extract_restaurant_events --determine_rating_thresholds > output/output.txt

      - name: Convert output to HTML
        run: |
          echo "<html><body><pre>" > output/index.html
          cat output/output.txt >> output/index.html
          echo "</pre></body></html>" >> output/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
